#include "holyc.h"
#include "parser.c"
#include <windows.h>

// Windows-specific assembly output
void GenerateCodeWindows(Parser* parser, const char* outputPath) {
    HANDLE file = CreateFileA(outputPath, GENERIC_WRITE, 0, NULL,
                           CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
    if (file == INVALID_HANDLE_VALUE) {
        Print("Failed to create output file\n");
        return;
    }

    // TODO: Implement code generation logic
    const char* asmHeader = 
        "; Generated by HolyC Compiler for Windows\n"
        "section .text\n"
        "global _main\n"
        "extern _printf\n\n"
        "_main:\n"
        "    push ebp\n"
        "    mov ebp, esp\n\n";
    
    DWORD bytesWritten;
    WriteFile(file, asmHeader, strlen(asmHeader), &bytesWritten, NULL);
    
    // TODO: Write generated assembly code
    const char* asmFooter = 
        "    mov esp, ebp\n"
        "    pop ebp\n"
        "    ret\n";
    
    WriteFile(file, asmFooter, strlen(asmFooter), &bytesWritten, NULL);
    CloseHandle(file);
}

// Main code generation function
void Generate(Parser* parser, const char* outputPath) {
    GenerateCodeWindows(parser, outputPath);
}